# Generated by Django 5.0.6 on 2024-05-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_artist_manufacturer_album_car_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='car',
            name='company_that_makes_it',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
