# Generated by Django 5.0.6 on 2024-05-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_book_bookdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registered_on', models.DateField()),
                ('account_type', models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum')], default='R', max_length=1)),
            ],
        ),
    ]
