# Generated by Django 5.0.6 on 2024-05-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
