# Generated by Django 5.0.6 on 2024-05-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='general_public',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='general_public',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='general_public',
            new_name='user',
        ),
    ]
