# Generated by Django 5.0.6 on 2024-06-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
