# Generated by Django 5.0.6 on 2024-07-01 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Romantic', 'Romantic'), ('Mystery', 'Mystery'), ('Biography', 'Biography')], default='Fantasy', max_length=10)),
                ('published_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
