# Generated by Django 5.0.6 on 2024-06-20 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Act'), ('Comedy', 'Com'), ('Animation', 'Ani'), ('Thriller', 'Thr'), ('Adventure', 'Adv'), ('War', 'War'), ('Western', 'West'), ('Horror', 'Hor')], default='Action', max_length=50)),
                ('language', models.CharField(choices=[('Eng', 'English'), ('Hin', 'Hindi'), ('Nep', 'Nepali'), ('Ita', 'Italian'), ('Spa', 'Spanish'), ('Kor', 'Korean'), ('Jap', 'Japanese')], default='Eng', max_length=50)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='Hello World')),
                ('highlighted', models.TextField(blank=True, default='Default Highlighted Text')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
    ]
