# Generated by Django 5.0.6 on 2024-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_rename_date_of_birth_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=None),
        ),
    ]
