# Generated by Django 5.0.6 on 2024-06-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0006_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvapp.basemodel')),
                ('location', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('SEE', 'School'), ('+2', 'High School'), ('Bachelor', 'College'), ('Master', 'University')], max_length=100)),
                ('grade', models.FloatField(blank=True)),
                ('enroll_date', models.DateField(blank=True)),
                ('passed_date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cvapp.basemodel',),
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
