# Generated by Django 5.0.6 on 2024-07-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_requestbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestbook",
            name="assign_book",
        ),
    ]
